server:
        port : 7022
spring:
    profiles:
          active:
    datasource:
            url: jdbc:mysql://localhost:3306/spider?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
            username: root
            password: root
            driverClassName: com.mysql.jdbc.Driver
    data:
            mongodb:
                    host: localhost
                    database: items
    redis:
            host: localhost
            port: 6379
            pool:
                  max-idle: 8
                  min-idle: 0
                  max-active: 8
                  max-wait: -1
logging:
  file: /usr/local/pro/logs/spider.log





