server:
        port : 7022
spring:
    profiles:
          active:
                  max-idle: 8
                  min-idle: 0
                  max-active: 8
                  max-wait: -1
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    data:
      elasticsearch:
        cluster-nodes: 172.19.26.63:9300
        cluster-name: elasticsearch
        repositories:
          enabled: false
    redis:
      host: 172.19.26.63
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 1
          min-idle: 0
      timeout: 0
      database: 0